export interface FAQ { q: string; a: string; }

type ProductType =
  | 'cosmetic' | 'kraft' | 'soap' | 'gift' | 'pillow'
  | 'rigid' | 'bakery' | 'display' | 'retail' | 'food'
  | 'candle' | 'corrugated' | 'mailer' | 'cbd' | 'pharma'
  | 'chocolate' | 'popcorn' | 'match' | 'cardboard'
  | 'business_card' | 'sticker' | 'folder' | 'pizza' | 'tray'
  | 'christmas' | 'beverage' | 'candy' | 'general';

function detectType(name: string, categories: string[]): ProductType {
  const n = name.toLowerCase();
  const c = categories.join(' ').toLowerCase();
  if (n.includes('christmas') || n.includes('xmas')) return 'christmas';
  if (n.includes('pizza')) return 'pizza';
  if (n.includes('popcorn')) return 'popcorn';
  if (n.includes('hot chocolate bomb') || (n.includes('chocolate') && !n.includes('kraft')) || n.includes('truffle')) return 'chocolate';
  if ((n.includes('match') && n.includes('box')) || c.includes('match box')) return 'match';
  if (n.includes('business card') || c.includes('business card')) return 'business_card';
  if (n.includes('sticker') || (n.includes(' label') && !n.includes('lip balm') && !n.includes('candle label')) || c.includes('sticker') || c.includes('label')) return 'sticker';
  if (n.includes('folder') || c.includes('folder')) return 'folder';
  if (n.includes('candle')) return 'candle';
  if (n.includes('cbd') || n.includes('vape') || n.includes('tincture')) return 'cbd';
  if (/\bpill\b/.test(n) || n.includes('medicine') || n.includes('lab box') || c.includes('pharmaceutical')) return 'pharma';
  if (n.includes('pillow box') || c.includes('pillow box')) return 'pillow';
  if (n.includes('corrugated')) return 'corrugated';
  if (n.includes('mailer') || (n.includes('shipping') && n.includes('box')) || n.includes('postal box')) return 'mailer';
  if (n.includes('display')) return 'display';
  if (n.includes('rigid')) return 'rigid';
  if (n.includes('tray') || c.includes('tray')) return 'tray';
  if (n.includes('candy') || c.includes('candy')) return 'candy';
  if (n.includes('coffee') || (n.includes('tea') && n.includes('box')) || c.includes('beverage')) return 'beverage';
  if (n.includes('brown') || c.includes('brown boxes')) return 'kraft';
  if (n.includes('kraft')) return 'kraft';
  if (n.includes('bakery') || n.includes('pastry') || n.includes('cake') || n.includes('biscotti') || n.includes('bagel') || n.includes('cookie') || c.includes('bakery')) return 'bakery';
  if (n.includes('burger') || n.includes('hot dog') || n.includes('french fry') || n.includes('macaron') || n.includes('pasta') || n.includes('gummy') || n.includes('frozen') || n.includes('fast food') || n.includes('fried chicken') || n.includes('cone sleeve') || (n.includes('food') && (n.includes('box') || n.includes('pack'))) || c.includes('food packaging')) return 'food';
  if (n.includes('soap')) return 'soap';
  if (n.includes('cream') || n.includes('perfume') || n.includes('lipstick') || n.includes('lip') || n.includes('eyelash') || n.includes('lotion') || n.includes('essential oil') || n.includes('beard oil') || n.includes('hair extension') || n.includes('cosmetic') || n.includes('beauty') || c.includes('cosmetic')) return 'cosmetic';
  if (n.includes('gift') || n.includes('scarf') || n.includes('ribbon') || n.includes('flower') || n.includes('necklace') || n.includes('earring') || n.includes('promotional') || n.includes('holiday') || c.includes('gift')) return 'gift';
  if (n.includes('retail') || n.includes('hanger') || c.includes('retail')) return 'retail';
  if (n.includes('cardboard') || c.includes('cardboard')) return 'cardboard';
  return 'general';
}

const TYPE_FAQS: Record<ProductType, (name: string, phone: string) => FAQ[]> = {

  cosmetic: (name, phone) => [
    { q: `What board is typically used for ${name}?`, a: `The standard substrate for ${name} is SBS (Solid Bleached Sulphate) clay board in 300–400 gsm. This white, coated board delivers excellent ink adhesion, outstanding CMYK colour fidelity, and a smooth surface that accepts all premium surface finishes — gloss lamination, soft-touch matte, spot UV, and hot foil stamping. For brands seeking a natural or eco-aligned aesthetic, FSC-certified white kraft board is also available. Rigid greyboard (1,200–2,400 gsm) is used for luxury cosmetic boxes requiring a premium structural weight.` },
    { q: `Can you match our exact brand colours on ${name}?`, a: `Yes. We offer Pantone spot colour matching on all ${name} orders, which ensures colour consistency across multiple print runs and across different packaging formats within your product range. For brands where CMYK printing achieves sufficient colour accuracy, we manage colour proofing to a tight tolerance standard and provide a colour-matched digital proof before production begins. If colour consistency across batches is critical for your brand, Pantone matching is the recommended specification.` },
    { q: `What finishes work best for premium ${name}?`, a: `Soft-touch matte lamination is the most requested finish for premium cosmetic packaging in Australia — its velvet-like tactile character creates a first-impression quality that strongly signals premium positioning. Matte lamination combined with spot UV varnish over the logo and key design elements is a highly effective combination, creating visual contrast that draws the eye to your brand mark. Gold hot foil stamping on a matte or soft-touch base is a popular choice for fragrance and luxury skincare brands. All of these finishes can be combined on a single order.` },
    { q: `Is there a minimum order quantity for ${name}?`, a: `No — we have no minimum order quantity. Independent beauty brands placing an initial production run of 100 units receive the same level of production quality and design support as established brands ordering 50,000 units. Pricing scales with volume and every quote includes a tiered breakdown across multiple quantity levels so you can identify the most cost-effective run size for your current demand.` },
    { q: `How long does production take for ${name}?`, a: `Standard production is 7–14 business days from the date your artwork is formally approved. Express turnaround (4–7 business days) is available for urgent orders — contact our team before placing your order to confirm express availability for your specific specification. The design process before approval typically takes 3–5 business days from the time your brief is confirmed.` },
    { q: `Can I see a physical sample of ${name} before full production?`, a: `Yes. Pre-production physical samples can be arranged for most cosmetic packaging formats — contact our team to discuss lead time and cost for your specific configuration. For most orders, the 3D digital proof and flat dieline we provide before production begins are sufficient for approval, as they allow you to verify dimensions, colour, layout, and finish specification with precision. Physical samples are most valuable for tactile finish verification on options such as soft-touch lamination or embossing.` },
    { q: `Do you offer eco-friendly options for ${name}?`, a: `Yes. FSC-certified kraft board, recycled SBS variants, and soy-based printing inks are all available for ${name} orders. These options are particularly relevant for beauty brands with sustainability commitments or brands marketing to eco-conscious consumers who actively scrutinise packaging credentials. Our team can confirm which specific eco certifications apply to your chosen substrate in the quoting process.` },
    { q: `What artwork file format should I supply for ${name}?`, a: `We accept Adobe Illustrator (AI), print-ready PDF, EPS, and high-resolution TIFF files at a minimum of 300 DPI at the intended print size, with 3mm bleed on all sides and all fonts outlined. If you are working with an external designer, we can supply a structural dieline template for your ${name} format for them to build artwork within. If you have no existing artwork, our in-house design team will create it from scratch at no charge.` },
    { q: `How do I get a quote for ${name}?`, a: `Complete the quote form on this page with your packaging dimensions, quantity, substrate preference, and finish requirements. Our team responds within 24 business hours with a detailed, itemised quote at no obligation. You can also reach us directly on ${phone} to discuss your brief before submitting a formal quote request.` },
    { q: `What quality guarantee applies to ${name}?`, a: `Every order we produce is backed by a quality guarantee. If your ${name} contain a manufacturing defect, a structural fault, or a print result that does not match your approved artwork, we will reprint or refund the affected portion of the order — no lengthy disputes or bureaucratic process. Contact our team within 7 days of receiving your order if you identify a quality concern and we will resolve it promptly.` },
  ],

  kraft: (name, phone) => [
    { q: `What is the difference between unbleached and bleached kraft for ${name}?`, a: `Unbleached kraft board retains the natural brown colour of the wood pulp it is made from — it produces the familiar warm, earthy aesthetic that artisan, natural, and eco-aligned brands use deliberately as a visual signal. Bleached kraft is processed to a white or light cream surface while maintaining the structural and sustainability characteristics of kraft board — it provides a cleaner printing surface for brands that want to print full-colour artwork accurately on a kraft substrate. Both are available in FSC-certified grades for our ${name} range.` },
    { q: `Can full colour be printed on ${name}?`, a: `Yes. Full-colour CMYK printing is available on both unbleached and bleached kraft variants. The natural warm tone of unbleached kraft shifts printed colours slightly warm — blues print with a green cast, whites are not achievable. This is a characteristic that many brands intentionally embrace because it contributes to an authentic, artisan print aesthetic. Bleached kraft produces more accurate colour reproduction, making it the better choice for brands that need to match specific brand colours precisely. Our design team will advise on colour adjustments for unbleached kraft artwork before printing.` },
    { q: `Is ${name} food-safe for use with food products?`, a: `FSC-certified kraft board is available in food-safe grades suitable for use with dry food products, baked goods, and packaged foods. Direct contact food applications require food-safe interior liners and food-safe adhesive formulations — these are available for all kraft food packaging configurations. If your ${name} will be in direct contact with food, advise our team at the quoting stage so the correct food-contact certified materials are specified from the outset.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. We produce ${name} in quantities from a single prototype through to high-volume wholesale runs. Pricing scales with quantity — every quote includes a tiered breakdown across multiple quantity levels so you can choose the run size that best balances per-unit cost with your current demand.` },
    { q: `What eco certifications apply to ${name}?`, a: `Our FSC-certified kraft board carries Forest Stewardship Council chain-of-custody certification, which confirms that the wood pulp used in the board originates from responsibly managed forests. Soy-based inks are used as standard on kraft variants — these produce lower VOC emissions than petroleum-based inks and are compostable alongside the packaging itself. If your brand makes specific sustainability claims about your packaging, our team can provide the relevant material certification documentation.` },
    { q: `What finish options are available on ${name}?`, a: `Kraft board accepts matte aqueous coating (the most common finish — provides a light protective layer while maintaining the natural hand feel of the kraft surface), spot UV on bleached kraft variants, and hot foil stamping in gold, copper, silver, and custom colours. Gloss lamination on unbleached kraft is technically possible but typically not specified because it conflicts with the natural aesthetic the material is chosen for. Embossing and debossing are available for brand marks.` },
    { q: `How quickly can ${name} be produced?`, a: `Standard production is 7–14 business days from artwork approval. Express production (4–7 business days) is available on request — confirm express availability with our team before submitting your order. The pre-production design process typically takes 3–5 business days from brief confirmation.` },
    { q: `What size range is available for ${name}?`, a: `All dimensions are fully custom. We do not operate a standard size catalogue — your ${name} are produced to the exact internal or external measurements your product requires. If you are unsure of the right box dimensions for your product, share the product's measurements and our team will recommend the optimal packaging size based on the product dimensions, any required insert or padding, and the structural format of the box.` },
    { q: `How do I get pricing for ${name}?`, a: `Use the quote form on this page or call us on ${phone}. Include your box dimensions, quantity, preferred kraft variant (unbleached or bleached), finish requirements, and any existing artwork. We respond with full pricing within 24 business hours.` },
  ],

  soap: (name, phone) => [
    { q: `What materials are recommended for ${name}?`, a: `Natural unbleached kraft board is the most commonly specified material for artisan and handmade soap packaging — it communicates natural ingredients and sustainable production values at the visual level, before the customer reads any copy. SBS clay board (300–400 gsm) is specified for soap brands seeking vivid full-colour printing and a polished retail aesthetic. Rigid greyboard is used for luxury soap gift sets. All materials are available in FSC-certified grades appropriate for eco-committed soap brands.` },
    { q: `Can ${name} include a windowed panel?`, a: `Yes. Window panels are a very popular feature for ${name} — they allow the soap's colour, texture, shape, and any embedded botanicals to serve as a visual merchandising element within the packaging. Window shapes can be rectangular, oval, arch, or custom die-cut to complement your brand design. The window panel uses a food-safe PET film insert. Note that some surface finishes (particularly gloss and soft-touch lamination) interact differently with die-cut window edges — our design team will advise on the most compatible finish for your windowed configuration.` },
    { q: `What closure types are available for ${name}?`, a: `Closure options include the standard tuck-end (top and bottom flaps tuck into the box — the most common and cost-effective format), lock-bottom construction (the base is locked at assembly rather than tucked — preferred for heavier soaps), and belly band format (a strip of printed card wraps around an unwrapped or lightly wrapped soap — the most minimal packaging option for boutique and market applications). Each closure type has different implications for assembly speed, structural security, and retail presentation.` },
    { q: `Is there a minimum order quantity for ${name}?`, a: `No minimum. Artisan soap makers ordering 50–100 units for a single retail account receive the same design support and production quality as wholesale soap producers ordering 10,000+ units. Pricing scales with quantity and our quotes include tiered pricing so you can compare costs across different production volumes.` },
    { q: `How do I ensure the dimensions fit my soap bars accurately?`, a: `Provide us with the dimensions of your soap bar (length, width, height) and any tolerance you require for ease of insertion and removal. Our structural engineers will design the dieline around those measurements — specifying internal clearances that allow the soap to slide in and out without being so loose that it shifts in transit. We provide a 3D digital proof of the dimensioned box before production begins.` },
    { q: `Are ${name} suitable for storage in humid environments like bathrooms?`, a: `Standard kraft and SBS cardboard boxes are not designed for prolonged exposure to high humidity — moisture will soften the board over time. For ${name} that will be stored in bathroom conditions, we recommend specifying a moisture-resistant surface coating or advising customers that the box is a retail display and storage format rather than an in-bathroom keeper. Many soap brands use their packaging for retail display and switch to a soap dish or ceramic holder for in-use storage.` },
    { q: `How long does production take for ${name}?`, a: `Standard turnaround is 7–14 business days from artwork approval. Design typically takes 3–5 business days from brief confirmation. Express options are available — contact us before ordering to confirm availability for your timeline.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include your soap bar dimensions, quantity, preferred material (kraft or SBS), finish preference, and whether a window is required. We respond within 24 hours.` },
  ],

  gift: (name, phone) => [
    { q: `What structural format is most suitable for ${name}?`, a: `The most appropriate structure depends on the product's weight, the price positioning, and the unboxing experience you want to create. Rigid lid-and-base boxes (greyboard 1,200–2,400 gsm) are preferred for luxury gifting where the weight of the box itself communicates quality. Folding cartons (SBS 350–450 gsm) with tissue inserts are used for mid-tier gifting where cost efficiency alongside presentation quality is the brief. Magnetic closure boxes provide the premium snap-shut opening experience without the higher production cost of a fully rigid construction.` },
    { q: `Can ${name} include ribbon pulls, magnetic closures, or internal tissue?`, a: `Yes to all three. Ribbon pull inserts are a popular upgrade on rigid ${name} — the ribbon allows the lid to be removed smoothly and adds a ceremonial quality to the unboxing moment. Magnetic closure strips are embedded in the lid and base panel to allow the box to open and close with a satisfying snap. Internal tissue paper, satin or velvet liner, foam inserts, and cardboard dividers are all available as interior configuration options to frame and protect the product inside.` },
    { q: `What finishes are most effective for premium ${name}?`, a: `Soft-touch matte lamination is the benchmark finish for premium gift packaging in Australia — its velvet-like surface texture communicates luxury positioning immediately upon handling. Gold or silver hot foil stamping on a matte or soft-touch base is the most impactful embellishment for gift packaging where the brand mark or product name needs a metallic accent. Spot UV varnish over a matte base creates visual contrast that draws the eye to specific design elements. Embossing provides tactile dimension to brand marks and typographic elements that are typically central to the gift box design.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum. Small businesses ordering 50 units for a boutique retail account and corporate companies ordering 5,000 branded gift boxes both receive the same level of design support and production quality. Pricing is tiered by volume — our quotes include breakdowns across multiple quantity levels.` },
    { q: `How do I specify the right size for ${name}?`, a: `Provide the dimensions of the products going inside the box — ideally the combined length, width, and height of the product and any wrapping, insert, or padding. Our structural engineers design the box dieline around those dimensions, specifying internal clearances that hold the product securely without creating excess headspace. We provide a 3D digital proof of the dimensioned box before production begins so you can verify the fit visually.` },
    { q: `Can ${name} be personalised for individual recipients?`, a: `Variable data printing is available for ${name} orders where individual unit personalisation (name, message, or unique code) is required. This technique is used for corporate gifting programmes where each box is addressed to a specific recipient, for wedding favours with personalised names, and for membership or loyalty gift programmes. Contact our team to discuss the personalisation specification — it affects both the artwork preparation and the print method used.` },
    { q: `How long does production take for ${name}?`, a: `Standard production is 7–14 business days from artwork approval. Rigid box formats involving greyboard construction may require 10–14 business days due to the additional production steps involved. Express options are available on some formats — confirm with our team before ordering if you have a specific delivery deadline.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call us on ${phone}. Include your product dimensions, preferred format (folding carton or rigid box), quantity, finish requirements, and any brief for the design. We respond with a detailed quote within 24 hours.` },
  ],

  pillow: (name, phone) => [
    { q: `What products are typically packaged in ${name}?`, a: `The pillow box format is best suited to small-to-medium products that do not require a flat base to stand upright — jewellery (rings, earrings, bracelets, pendants), small accessories (hair ties, clips, bookmarks), artisan beauty products (bath bombs, soaps, small candles), and gift items (chocolates, confectionery, small toys). The curved sides and push-in closure make the format most appropriate for products where presentation and ease of display are the primary brief, rather than structural rigidity for heavy or fragile items.` },
    { q: `Can ${name} be printed in full colour?`, a: `Yes. Full-colour CMYK printing is available on all ${name} formats on both SBS clay board and bleached kraft variants. SBS board delivers the most vibrant and colour-accurate results; kraft board produces a warmer, more organic print character that many artisan brands prefer. All finishes available on standard carton formats — gloss lamination, matte lamination, spot UV, foil stamping, embossing — are also available on ${name}.` },
    { q: `What size range is available for ${name}?`, a: `We produce ${name} in sizes ranging from small jewellery formats (approximately 60 × 35 mm flat dimensions) through to large gift-item formats (approximately 200 × 100 mm and above). All dimensions are custom — if a standard size does not suit your product, we design the dieline around your specific requirements. Providing your product's length, width, and height allows us to recommend the optimal flat dimensions for the pillow box format.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum. Small quantities are entirely acceptable and receive the same level of design support and production quality as large runs. Pricing scales with quantity — our quotes include tiered pricing across multiple quantity levels for easy comparison.` },
    { q: `How are ${name} assembled?`, a: `Pillow boxes are supplied flat-packed for storage and shipping efficiency. Assembly involves folding along the pre-scored crease lines and pushing the two end panels inward to form the curved pillow shape — the product is then inserted and the end panels are tucked in to close. No tape or adhesive is required for assembly. The format is well-suited to in-house packing operations where staff assemble boxes as products are packed.` },
    { q: `Can ${name} be made from eco-friendly materials?`, a: `Yes. FSC-certified kraft board and recycled SBS board variants are available for ${name} orders. Soy-based inks are used as standard on kraft variants. If you are making eco-friendly claims on your product, our team can provide the relevant material certification documentation for the substrate used in your order.` },
    { q: `How do I get a quote for ${name}?`, a: `Complete the form on this page or call ${phone}. Include the flat dimensions you require (or your product dimensions so we can calculate them), the quantity, your preferred substrate, and any finish requirements. We respond within 24 hours.` },
  ],

  rigid: (name, phone) => [
    { q: `What is the difference between rigid boxes and folding cartons?`, a: `Rigid boxes are constructed from thick greyboard (1,200–2,400 gsm) that is pre-formed and permanently glued into a lid-and-base structure — the box does not fold flat. Folding cartons are produced from thinner SBS board (300–450 gsm) and are flat-packed until assembled by the customer. Rigid boxes deliver a substantially heavier, more premium tactile experience; folding cartons are more cost-effective and storage-efficient. For ${name}, the choice between formats depends on the product's price positioning, the required unboxing experience, and the budget for packaging per unit.` },
    { q: `What greyboard thickness is available for ${name}?`, a: `We produce ${name} in greyboard thicknesses of 1 mm, 1.5 mm, 2 mm, and 3 mm. The appropriate thickness depends on the product weight (heavier products require thicker board to prevent the base from deflecting), the box dimensions (larger boxes require thicker board to maintain structural rigidity), and the tactile quality required (thicker board produces a heavier, more premium-feeling box). Our team will recommend the correct thickness based on your product specifications in the quoting process.` },
    { q: `What wrapping paper options are available for the exterior of ${name}?`, a: `The exterior wrapping paper of ${name} is a key determinant of the finished aesthetic. Options include gloss art paper (vivid colour, high shine), matte art paper (refined, fingerprint-resistant), textured uncoated stock (tactile, premium, often used for luxury fragrance and jewellery brands), soft-touch paper (velvet-like texture), and specialty papers including linen, felt, and metallic variants. The wrapping paper can be printed with your full-colour artwork, a solid colour, or a pattern — the design possibilities are extensive.` },
    { q: `Can ${name} include a magnetic closure?`, a: `Yes. Magnetic closure strips are embedded in both the lid and the base panel during the construction process, allowing the lid to snap shut securely without any additional fastening. The magnets are invisible from the exterior and do not affect the print surface of the wrapping paper. This is one of the most popular upgrades on luxury ${name} — the tactile snap of the closure reinforces the premium positioning of the product inside.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. Rigid box production involves more production steps than folding carton work — particularly the greyboard cutting, forming, and wrapping process — which means the per-unit cost at very low quantities reflects those additional steps. However, we do not impose a minimum, and many of our clients order small prototype quantities before committing to full production runs.` },
    { q: `How long does production take for ${name}?`, a: `Standard production for ${name} is 10–14 business days from artwork approval, reflecting the additional construction steps involved in rigid box manufacturing. Express production is available on some rigid formats — contact our team to confirm lead time availability before submitting your order.` },
    { q: `Can ${name} include custom interior lining?`, a: `Yes. Interior options include plain white board, full-colour printed interior, velvet-like flocked paper liner, silk or satin liner, foam cavity inserts, vacuum-formed plastic trays, and cardboard divider configurations. The interior specification significantly affects both the perceived quality of the unboxing experience and the unit cost — our team will discuss the options that deliver your required result within your budget.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include the product dimensions (to specify lid and base sizes), the product weight (to determine greyboard thickness), the quantity, your preferred exterior wrap and finish, and any interior or closure requirements. We respond with full pricing within 24 hours.` },
  ],

  bakery: (name, phone) => [
    { q: `Are ${name} food-safe?`, a: `Yes. All ${name} we produce use food-safe board, food-safe adhesive formulations, and printing inks that comply with Australian food contact packaging regulations. We can provide material safety data and food contact certification documentation for your specific substrate on request — this is sometimes required by food safety auditors or retail buyers specifying packaging requirements for their supplier base.` },
    { q: `Can ${name} be greaseproof for high-fat pastries and baked goods?`, a: `Yes. We apply a greaseproof interior coating to ${name} used for products with high oil or moisture content — croissants, Danish pastries, butter-rich cakes, fried products, and filled pastries that would otherwise saturate uncoated board. The coating prevents oil migration to the exterior surface, which would compromise both the structural integrity of the box and the printed branding on the outside. If your products have a high fat content, advise our team at the quoting stage so the correct interior specification is applied.` },
    { q: `Can ${name} include a windowed panel?`, a: `Yes. Window panels are a popular feature for ${name} — particularly for cakes, tarts, and artisan pastries where the visual appearance of the product is the primary sales driver at point of purchase. Window shapes can be rectangular, oval, arch, or custom die-cut. The window uses a food-safe, heat-resistant PET film. For products displayed at ambient temperature, standard PET is used; for products that go directly from oven or warming cabinet into the box, we recommend a heat-resistant PET variant.` },
    { q: `What is the minimum order for ${name}?`, a: `No minimum. Independent patisseries ordering 100 units for a seasonal product launch and commercial bakeries ordering 20,000 units for regular replenishment both place orders with us without restriction. Pricing is tiered by volume — our quotes always include a breakdown across multiple quantity levels.` },
    { q: `What substrate is best for ${name}?`, a: `SBS clay board (300–400 gsm) is the standard substrate for most ${name} — it provides a bright white printing surface, good structural rigidity for the typical weight range of baked goods, and accepts all standard finish options. Unbleached kraft board is specified for artisan and health food bakery brands that want the packaging to communicate natural, wholesome values in line with their product positioning. Recycled board is also available for sustainability-committed brands.` },
    { q: `Can ${name} go in a refrigerator?`, a: `Standard SBS cardboard boxes can be used in refrigerated environments for short periods (such as transit from production to a retail chiller display). Prolonged refrigeration exposure will cause condensation on the box surface as it warms to room temperature, which may affect the print quality and structural integrity over time. For products that live permanently in refrigerated display, discuss your specific application with our team — we can recommend the most appropriate material and coating specification.` },
    { q: `How quickly can ${name} be produced?`, a: `Standard production is 7–14 business days from artwork approval. Design typically takes 3–5 business days. Express production is available — contact us to confirm availability before ordering if you have an urgent timeline.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Provide the product dimensions (the baked goods you need to fit inside), the quantity, your preferred substrate, and any finish or window requirements. Attach any existing brand files or logo assets — our team responds within 24 hours.` },
  ],

  display: (name, phone) => [
    { q: `What structural formats are available for ${name}?`, a: `Counter display packaging (PDQ trays) sits on a checkout counter or service desk and holds individual product units in a forward-facing arrangement for easy customer self-selection. Floor display stands are freestanding structures that can hold significantly larger product quantities and are typically placed at the end of aisles or at category entry points. Shelf-ready packaging (SRP) is a shipper that converts into a shelf display unit when the lid or front panel is removed — used widely in supermarket and convenience channel distribution. Each format has specific structural requirements that determine the board grade and construction method.` },
    { q: `What print quality is achievable on ${name}?`, a: `Full-colour CMYK printing is standard for all ${name} produced from SBS cardboard — this delivers photographic quality colour reproduction on the header card and all brand communication panels. For corrugated floor display formats, we offer litho laminate printing (full-colour offset print on smooth art paper laminated to the corrugated substrate), which achieves near-retail-carton print quality on a structurally robust display format. Flexographic printing on corrugated liner is an alternative for high-volume runs where cost efficiency is the priority over premium print quality.` },
    { q: `How many units does a ${name} typically hold?`, a: `The unit count varies significantly by product size and display format. Counter PDQ trays for impulse items such as confectionery, lip balms, or travel accessories typically hold 12–36 units. Floor display stands for larger FMCG products typically hold 24–96 units depending on the product footprint. We design the structure around your specific product dimensions and the unit count you specify — the display shelf width, depth, and divider configuration are all engineered to your product.` },
    { q: `Can ${name} be designed for rapid replenishment?`, a: `Yes. Display packaging designed for active retail environments should facilitate quick replenishment — our ${name} designs incorporate front-facing product slots, adequate depth for multiple units behind the front row, open sides for easy lateral loading, and structural configurations that allow staff to refill the display in seconds without fully disassembling it. Describe your retail environment and replenishment frequency when requesting a quote and we will factor these operational requirements into the structural design.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum. We produce ${name} from a small trial quantity through to high-volume production for national retail rollouts.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include the retail environment (counter, floor, or shelf), the product dimensions and individual unit weight, the units-per-display count, the total quantity of displays, and any retail buyer specifications. We respond within 24 hours.` },
  ],

  retail: (name, phone) => [
    { q: `What substrate options are available for ${name}?`, a: `Our ${name} are produced from 300–450 gsm SBS clay board as the standard substrate — a white, caliper-consistent material that delivers vibrant CMYK printing and accepts all surface finishes. Kraft board (300–400 gsm) is available for brands seeking a natural aesthetic. Rigid greyboard is specified for premium or luxury retail formats. Specialty stocks including textured paper, linen-finish board, and metallic substrates can be sourced for brands seeking distinctive material character on shelf.` },
    { q: `Can ${name} be produced in custom sizes?`, a: `Yes — all dimensions are fully custom. We do not use a standard size catalogue. Your ${name} are produced to your exact product dimensions, with our structural engineers designing the dieline based on the internal measurements your product requires and the structural format (tuck-end, lock-bottom, sleeve, etc.) you specify.` },
    { q: `What print finishes are most effective for retail shelf presence?`, a: `Gloss lamination produces maximum colour vibrancy on shelf — colours appear more saturated and light-reflective. Matte lamination delivers a sophisticated, non-reflective surface that photographs well and resists fingerprints. Spot UV applied selectively over a matte base is effective at directing customer attention to your brand mark or key product descriptor. Pantone spot colour matching is recommended for brands where the exact colour of key brand elements (logotype, icon, brand line) must be consistent across all packaging formats and print runs.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. We produce from small prototype runs through to high-volume wholesale replenishment orders with the same quality standards throughout.` },
    { q: `How long does production take?`, a: `Standard production is 7–14 business days from artwork approval. The pre-production design and dieline step typically takes 3–5 business days from brief confirmation. Express turnaround is available on request — confirm availability with our team before placing your order.` },
    { q: `How do I get a quote for ${name}?`, a: `Complete the form on this page or call ${phone}. Include your product dimensions, quantity, substrate preference, finish requirements, and any existing design files. We respond within 24 hours with an itemised quote.` },
  ],

  food: (name, phone) => [
    { q: `Are ${name} food-safe and compliant with Australian standards?`, a: `Yes. All ${name} we produce use board, adhesives, and printing inks that comply with Australian food contact packaging regulations. Food-safe material certification is available for the specific substrates used in your order — this documentation is sometimes required by food safety auditors, retail buyers, or food regulatory compliance programmes. If you need specific certification documentation, advise our team at the quoting stage.` },
    { q: `Can ${name} handle greasy or moist food products?`, a: `Yes. We apply greaseproof interior coatings and moisture-resistant barrier treatments to ${name} used with high-fat or high-moisture food products. The specific coating type is selected based on the product — light oily products (baked goods, sandwiches) use an aqueous grease-resistant coating; heavier oil applications (fried foods, heavily dressed meals) use a more robust barrier specification. Advise our team of the food product type when requesting a quote so the correct interior coating is specified.` },
    { q: `Are the inks used on ${name} food-safe?`, a: `Yes. All printing inks used on ${name} are food-safe formulations compliant with the relevant Australian and international food contact ink standards. We use inks from certified food packaging ink suppliers, and the ink formulations are selected to be appropriate for indirect and, where specified, direct food contact applications.` },
    { q: `Can ${name} be branded with our logo and colours?`, a: `Yes — full-colour CMYK branding is available on all ${name}. Your logo, brand colours, product imagery, and any required food labelling information (ingredients, allergens, nutritional information) can all be incorporated into the print design. If your product has mandatory food labelling requirements, share the text content with our design team and they will incorporate it into the artwork layout.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. Food businesses at all stages of growth — from a single café operator ordering 500 units of a custom takeaway box through to a national QSR chain ordering 500,000 units per month — can place orders with us without restriction.` },
    { q: `How long does production take for ${name}?`, a: `Standard turnaround is 7–14 business days from artwork approval. Express options are available — contact us before ordering to confirm availability for your specific timeline requirement.` },
    { q: `How do I order ${name}?`, a: `Complete the form on this page or call ${phone}. Include the food product type, the packaging dimensions you need, the quantity, and whether any special coatings (greaseproof, moisture-resistant) are required. We respond within 24 hours with a food-safe material recommendation and full pricing.` },
  ],

  candle: (name, phone) => [
    { q: `What structural format is best for ${name}?`, a: `The most appropriate structure depends on the candle format you are packaging. Jar candles (glass or ceramic vessels) are typically packaged in a square or rectangular tuck-end or lock-bottom box — the base construction is critical for supporting the weight of the filled glass vessel. Pillar candles are typically packaged in a rectangular box with the candle standing vertically or lying horizontally, depending on its dimensions. Taper candles are packaged in long, narrow formats. Votive and tea light collections are typically packaged in multi-compartment boxes with individual inserts or dividers.` },
    { q: `What board weight is needed for ${name} containing glass vessels?`, a: `Glass jar candles require board weights at the heavier end of our standard range — 400–450 gsm SBS board is typical for folding carton formats housing filled jars. The base construction (lock-bottom rather than tuck-end) provides additional structural security for heavy vessels. For very heavy jar candles (500 g+ filled weight), rigid greyboard (1,200+ gsm) is recommended, as it provides the structural rigidity needed to prevent base deflection and protect the glass during transit and stacking in a retail environment.` },
    { q: `Can ${name} include an interior insert to hold the candle?`, a: `Yes. Cardboard inserts shaped to the candle vessel dimensions are a popular addition to ${name} — they hold the jar or pillar candle centred and stable within the box, preventing shifting during transit and elevating the presentation when the box is opened. Foam inserts, corrugated card inserts, and tissue paper padding are also available. For luxury candle gift sets, velvet-flocked card inserts are used to create a jewellery-box-style interior presentation.` },
    { q: `What finish is most popular for premium ${name}?`, a: `Soft-touch matte lamination is the most requested finish for premium candle packaging in Australia — the velvet-like surface texture aligns with the sensory positioning of luxury and lifestyle candle brands and creates a very strong shelf impression alongside branded candle packaging at higher price points. Kraft board with no lamination or a light aqueous coat is the most popular choice for artisan and eco-aligned candle brands. Gold foil stamping on either surface is a widely used embellishment for candle brands with a premium positioning.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum. Independent candle makers ordering 100 units for their first retail stockist and established candle brands replenishing 10,000 units of their full range both order with us without restriction.` },
    { q: `How quickly can ${name} be produced?`, a: `Standard production is 7–14 business days from artwork approval. Rigid board candle box formats (for heavier glass jars) may take 10–14 days due to the additional construction steps. Express options are available on folding carton formats — confirm with our team before ordering.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include the candle format (jar with vessel dimensions, pillar with height and diameter, taper, etc.), the filled weight of the candle, the quantity, your preferred substrate, and finish requirements. We respond within 24 hours.` },
  ],

  corrugated: (name, phone) => [
    { q: `What wall configuration is right for my ${name}?`, a: `Single wall corrugated (B or C flute, approximately 3–4 mm thick) is appropriate for most standard product shipping applications — products up to about 5–7 kg with normal fragility. Double wall (approximately 6–7 mm) is specified for heavier products, fragile items requiring additional compressive strength, or boxes that will be stacked under load in a warehouse environment. Triple wall (approximately 10–12 mm) is used for heavy industrial products, pallet-level shipping, and export applications where maximum BCT (Box Compression Test) strength is required. Our team recommends the correct wall configuration based on your product weight, fragility, and transit scenario.` },
    { q: `Can ${name} be printed in full colour?`, a: `Yes. Full-colour litho laminate printing is available for all ${name} — this involves printing on smooth art paper using offset or digital printing and then laminating that printed sheet to the corrugated substrate. The result is near-retail-carton print quality on a structurally robust corrugated box. Standard flexographic printing directly on the corrugated liner is also available for applications where cost efficiency and production speed are the priority over premium print quality.` },
    { q: `Can ${name} include branded interior printing?`, a: `Yes. Interior printing is available on ${name} for brands that want the unboxing experience to continue on the inside of the box — brand messaging, care instructions, or a welcome message printed on the interior panels. This is particularly popular for premium e-commerce brands where the delivery box is a core part of the customer brand experience.` },
    { q: `What is the BCT strength of ${name}?`, a: `BCT (Box Compression Test) strength depends on the flute configuration, board grade, and box dimensions — a larger box of the same board grade will have lower BCT than a smaller one due to increased panel span. For applications where stacking under specific load requirements is critical (warehouse storage, pallet shipping), provide the stacking height and load per pallet to our team and we will specify the board grade and wall configuration required to meet the BCT standard your logistics operation needs.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. Small businesses shipping their first 100 orders and large manufacturers ordering 100,000 corrugated boxes per month both place orders with us.` },
    { q: `How do I get a quote for ${name}?`, a: `Complete the form on this page or call ${phone}. Include your product dimensions and weight, the fragility level, the quantity, whether branded exterior or interior printing is required, and any stacking or pallet configuration requirements. We respond within 24 hours.` },
  ],

  mailer: (name, phone) => [
    { q: `What board weight is recommended for ${name}?`, a: `The board weight for ${name} is determined by the weight and fragility of the products being shipped. For lightweight apparel, accessories, or documents (under 500 g), rigid board mailers (350–400 gsm) provide a sleek, compact mailer format. For heavier or more fragile products, single wall corrugated B or E flute (3–4 mm) provides structural protection for standard courier transit. For fragile or heavy items, double wall corrugated is specified. Our team will recommend the correct board specification based on your product and the courier network you use.` },
    { q: `Can ${name} be assembled without tape?`, a: `Yes — self-locking mailer configurations are assembled using pre-scored fold lines and interlocking tabs, without requiring tape or adhesive. This is important for high-volume fulfilment operations where pack speed is a cost driver. Peel-and-seal tape closure strips are available on rigid board mailer formats where a clean, reusable-looking closure is preferred. Tear-strip features for easy customer opening can be incorporated into the design.` },
    { q: `What finish options are available on ${name}?`, a: `Full-colour exterior printing is available on all ${name}. For rigid board mailers, gloss and matte lamination are available as surface finishes. For corrugated mailers, litho laminate printing produces the highest quality exterior print. Standard flexographic printing on kraft liner is available for functional exterior printing where brand identity rather than premium print quality is the goal. Interior printing (brand message, care instructions, promotional offers) is available on both rigid and corrugated formats.` },
    { q: `Can ${name} include a custom interior?`, a: `Yes. Interior options include tissue paper (standard or custom printed), void fill inserts (crinkle paper, air pillows), foam padding, cardboard inserts shaped to product dimensions, and full-colour printed interior panels. The interior specification is as important as the exterior for brands where the unboxing experience is a deliberate part of the customer relationship — particularly for direct-to-consumer subscription brands and premium gift brands.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum. We serve everything from small e-commerce businesses ordering 200 mailer boxes to large fulfilment operations ordering 100,000+ units per run.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include your typical product dimensions and weight range, the quantity, whether rigid or corrugated board is preferred, and any interior or exterior print requirements. We respond within 24 hours.` },
  ],

  cbd: (name, phone) => [
    { q: `Do ${name} comply with Australian regulations for CBD products?`, a: `We produce ${name} with the panel configuration and structural features appropriate for the regulatory requirements applicable to your specific product and distribution channel. However, regulatory compliance for CBD and schedule-classified products in Australia is the responsibility of the brand and should be confirmed with your regulatory adviser before finalising packaging specifications. Our team can discuss the panel geometry, text field sizing, and child-resistant structural options — but the regulatory content and classification must be confirmed by your compliance team.` },
    { q: `Are child-resistant ${name} available?`, a: `Yes. We offer structural configurations with push-and-turn or squeeze-and-slide closure mechanisms appropriate for products requiring child-resistant packaging under Australian standards. These structural features must be designed into the box from the dieline stage — they cannot be added to a standard tuck-end carton after the fact. If child resistance is a requirement for your product, advise our team at the start of the quoting process.` },
    { q: `What substrate is recommended for ${name}?`, a: `300–400 gsm SBS clay board is the standard substrate for ${name} — it provides a clean white printing surface with excellent legibility for compliance text at small type sizes, accurate colour reproduction for brand elements, and a professional finish consistent with health and wellness product positioning. Matte lamination is the most common surface finish in this category — it creates a clean, understated aesthetic appropriate for health-adjacent products and provides good legibility for small-format regulatory text.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. Emerging wellness brands and established supplement companies both order without restriction.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include your product dimensions, the quantity, any compliance or regulatory panel requirements, and whether child-resistant closure is needed. We respond within 24 hours.` },
  ],

  pharma: (name, phone) => [
    { q: `What material certifications apply to ${name}?`, a: `Our ${name} are produced from pharmaceutical-grade SBS board with material safety data sheets (MSDS) and relevant food and pharmaceutical contact certifications available for the specific substrate used in your order. All adhesive formulations used in pharmaceutical packaging are selected for food and pharmaceutical contact safety. If your regulatory compliance programme requires specific material certification documentation, our team will provide the relevant certificates as part of the order documentation.` },
    { q: `Can ${name} accommodate serialisation or track-and-trace requirements?`, a: `Yes. We can incorporate serialisation panel areas (for barcode, 2D code, or QR code application), pre-printed lot number fields, and expiry date windows into the structural design of ${name}. If your product requires variable print data (individual serial codes, patient identifiers, or batch-specific information) printed in-line, advise our team — this affects the print method and may require digital printing for variable data fields.` },
    { q: `Can ${name} include tamper-evident features?`, a: `Yes. Tamper-evident gluing configurations, tear-strip seals, and score-to-break features can be incorporated into the structural design of ${name}. The specific tamper-evidence approach is selected based on your product's classification and the regulatory requirements applicable to your distribution channel. Discuss the required tamper-evidence standard with your regulatory team before briefing us — this ensures the structural design meets the applicable requirement from the dieline stage.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum. Compounding pharmacies ordering small specialist runs and pharmaceutical manufacturers ordering large-volume retail-channel cartons both order with us.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include your product dimensions, the regulatory classification (if known), compliance panel requirements, any serialisation or tamper-evidence requirements, and the quantity. We respond within 24 hours and treat all pharmaceutical packaging briefs with appropriate confidentiality.` },
  ],

  chocolate: (name, phone) => [
    { q: `Are ${name} food-safe for direct chocolate contact?`, a: `Yes. All ${name} we produce use food-grade board, food-safe interior liner paper for direct chocolate contact applications, and adhesive formulations compliant with Australian food contact packaging regulations. The interior liner used for direct chocolate contact is available in white and gold foil variants. If your chocolate will be in direct contact with the box interior (rather than individually wrapped), advise our team so the correct food-contact liner is specified from the outset.` },
    { q: `Can ${name} include custom compartment inserts?`, a: `Yes. Custom insert trays in cardboard, vacuum-formed PET, or flocked velvet-like material are available to hold individual chocolates in precise positions. Standard compartment configurations from 2 to 36 pieces are available; bespoke layouts for unusual assortment shapes or quantities are designed on a per-order basis. The insert material significantly affects the perceived quality of the unboxing experience — velvet-flocked trays are the premium choice for luxury gifting contexts; cardboard inserts are the cost-effective standard for mid-tier and retail formats.` },
    { q: `Can ${name} be refrigerated?`, a: `Standard SBS and rigid board boxes can be used in refrigerated retail display environments for standard display periods. Prolonged refrigeration (extended chiller storage) may cause condensation on the box surface as it warms, which can affect the exterior print and structural integrity over time. For products that live permanently in a refrigerated environment, discuss your specific application with our team — we can recommend moisture-resistant material options for extended chiller display scenarios.` },
    { q: `What finishes are most effective for luxury ${name}?`, a: `Hot gold foil stamping on a matte or soft-touch base is the most impactful finish for luxury chocolate packaging — the metallic contrast signals premium quality immediately. Embossed brand marks on the lid of rigid chocolate boxes create a tactile quality that distinguishes the packaging before it is even opened. Soft-touch matte lamination as the base finish provides the velvet-like tactile character that premium confectionery brands consistently specify for their flagship product lines.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. Artisan chocolatiers producing seasonal collections and national confectionery brands managing retail replenishment both order without restriction.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include the box dimensions (or the compartment count and chocolate dimensions), the quantity, the preferred exterior substrate and finish, and whether a custom insert tray is required. We respond within 24 hours.` },
  ],

  popcorn: (name, phone) => [
    { q: `Are ${name} food-safe?`, a: `Yes. All ${name} are produced from food-grade paperboard with food-safe interior coatings and printing inks compliant with Australian food contact packaging regulations. The grease-resistant interior coating is a standard inclusion on our popcorn packaging to prevent oil from buttered or flavoured popcorn from migrating to the printed exterior surface.` },
    { q: `What sizes are available for ${name}?`, a: `We produce ${name} in a range of standard serving sizes (small, medium, large, and jumbo) as well as custom dimensions for specialty applications (mini favour bags for events, sharing buckets for large-format cinema, retail take-home sizes). All dimensions are custom — if you need a specific serving volume, provide the capacity in millilitres or the popcorn weight at standard packing density and our team will recommend the appropriate box dimensions.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. Cinema operators ordering a full season's supply and specialty food brands ordering a boutique run for a market stall both order without restriction.` },
    { q: `How do I get a quote for ${name}?`, a: `Complete the form on this page or call ${phone}. Include the format (bucket, flat-pack carton, or windowed display), the serving size, the quantity, and your brand files. We respond within 24 hours.` },
  ],

  match: (name, phone) => [
    { q: `What are the dimensional tolerances for ${name}?`, a: `The dimensional relationship between the internal tray and the external sleeve is the critical specification for ${name}. We maintain a ±0.5 mm tolerance on both components to ensure a consistent sliding action — tight enough to hold the tray securely when the box is held, loose enough that the tray can be extracted smoothly with one hand. If you are filling the boxes with specific match lengths, provide the match dimensions so we can engineer the internal tray dimensions around them.` },
    { q: `Can ${name} include a strike strip?`, a: `Yes. A safety strike strip (red phosphorus friction surface) can be applied to the base or side panel of ${name} for functional matchbox applications. The strike strip is applied as a separate component during assembly. Decorative non-functional match boxes (for promotional or display use) are produced without a strike strip.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include the external sleeve dimensions, whether a strike strip is required, the quantity, and your design files. We respond within 24 hours.` },
  ],

  cardboard: (name, phone) => [
    { q: `What cardboard grades are available for ${name}?`, a: `Our ${name} are produced from SBS clay board in 250, 300, 350, 400, and 450 gsm, selected based on the product weight, structural requirements, and print specification. Lighter grades (250–300 gsm) are appropriate for lightweight products with simple structural requirements. Heavier grades (400–450 gsm) provide additional compressive strength for heavier products and taller structural formats. Our team recommends the most appropriate grade based on your product specifications.` },
    { q: `What structural formats are available for ${name}?`, a: `We produce ${name} in all standard structural formats: straight-tuck end, reverse-tuck end, auto-bottom lock, seal end, two-piece tray with lid, sleeve with insert tray, and fully custom die-cut structures. The most appropriate format depends on the product shape, the intended retail or dispatch environment, and the opening experience you want to deliver. If you have a specific structural requirement that is not listed, share it with our team — we can design a custom dieline from scratch.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity.` },
    { q: `How do I get a quote for ${name}?`, a: `Complete the form on this page or call ${phone}. Include your product dimensions, the quantity, your preferred board grade, the finish requirements, and the structural format if known. We respond within 24 hours with an itemised quote.` },
  ],

  business_card: (name, phone) => [
    { q: `What stock thickness is available for ${name}?`, a: `Our ${name} are produced from 350 to 700 gsm laminated board. Standard business cards use 350–400 gsm; ultra-thick premium cards use 500–700 gsm double-layer board (a 350 gsm sheet laminated with a colour or black core for a distinctive coloured edge effect). The appropriate thickness depends on your intended positioning — thicker cards create a stronger first impression and communicate higher quality when handed over.` },
    { q: `What finishes are available on ${name}?`, a: `All standard surface finishes are available on ${name}: gloss lamination, matte lamination, soft-touch matte (a velvet-like premium finish popular with design, photography, and creative professionals), spot UV (applied selectively over a matte base to create contrast around a logo, name, or key design element), hot gold or silver foil stamping, and rounded corners (a subtle but distinctive alternative to the standard square corner). These can be combined — soft-touch with spot UV is the most requested premium combination.` },
    { q: `Can ${name} include special die-cuts or shapes?`, a: `Yes. Custom die-cut business card shapes are available for brands that want a card format that stands out beyond the standard 90 × 55 mm rectangle. Common custom formats include square cards, cards with a corner cut, cards with a notch for a thumb-grip, and fully custom shapes that reference the business's product or industry. Custom die-cut cards require a slightly longer lead time for the die tool production step.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. We print from small personal quantities through to large corporate orders for national sales teams.` },
    { q: `How do I order ${name}?`, a: `Use the form on this page or call ${phone}. Include the quantity, preferred stock weight, finish, and whether you have existing artwork. If no artwork, our design team will create your card at no charge. We respond within 24 hours.` },
  ],

  sticker: (name, phone) => [
    { q: `What substrate is right for my ${name} application?`, a: `Substrate selection for ${name} depends entirely on where the sticker will be applied and how long it needs to last. Vinyl is the correct choice for outdoor applications, vehicle graphics, and any surface exposed to UV, moisture, or abrasion — it is dimensionally stable and resistant to fading. Polypropylene is used for product and packaging labels that need a no-label look on glass or transparent packaging. White or kraft paper is used for product labels, packaging seals, and short-dwell-time retail applications. Advise our team of the intended application surface, environment, and required durability when requesting a quote.` },
    { q: `What adhesive types are available for ${name}?`, a: `Permanent adhesive is standard — it bonds securely and is not intended for removal without damage to the surface or the label. Removable adhesive is used for promotional labels, price stickers, and applications where the sticker needs to be peeled off without residue. High-tack adhesive is specified for difficult surfaces such as corrugated board, textured plastic, or matte-laminated cartons where standard permanent adhesive may not bond reliably. Advise our team of the application surface and required peel-off behaviour when requesting a quote.` },
    { q: `Can ${name} be supplied on rolls for automated application?`, a: `Yes. Roll format is standard for label applications that are applied using a labelling machine or dispenser. Sheet format is standard for hand-applied stickers and promotional materials. Roll core diameter, label gap, and wind direction (inside or outside wound) are all specified based on your applicator's requirements.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. We print from small artisan label quantities through to large industrial roll label runs.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include the sticker dimensions, the substrate type, the adhesive requirement, the supply format (sheet or roll), the quantity, and your design files. We respond within 24 hours.` },
  ],

  folder: (name, phone) => [
    { q: `What pocket configuration is available for ${name}?`, a: `Our ${name} are available in single pocket (one interior pocket on the right side, designed to hold standard A4 documents), double pocket (pockets on both left and right interior faces for separating different document categories), and with optional business card slots die-cut into the right pocket for card retention. Spine additions (a foldable spine strip between the two covers) are used for thicker document sets. All configurations are available in A4 and custom sizes.` },
    { q: `What paper stock is used for ${name}?`, a: `Our ${name} are produced from 350–400 gsm SBS clay board — the heavier end of standard printing paper weights, which provides the rigidity needed for a folder to maintain its structure when held and to resist bending during storage and transit. Gloss and matte lamination are applied over the full exterior surface to protect the print and provide the premium finish appropriate for a professional presentation product.` },
    { q: `What finish is most appropriate for corporate ${name}?`, a: `Matte lamination with spot UV on the logo and key typographic elements is the most popular finish for professional and corporate ${name} — the matte base creates an understated, high-quality impression, and the spot UV highlights draw the eye to the brand mark without appearing flashy. Gloss lamination is preferred for industries where vibrant colour impact is more important than a subdued premium aesthetic — real estate, events, and hospitality brands frequently specify gloss. Soft-touch lamination is available for firms that want a distinctly premium, velvet-like surface on their folder.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include the pocket configuration, the size, the quantity, the finish preference, and any existing brand files. We respond within 24 hours.` },
  ],

  pizza: (name, phone) => [
    { q: `What sizes are available for ${name}?`, a: `We produce ${name} in all standard pizza sizes — 8", 10", 12", 14", and 16" square formats — as well as custom dimensions for non-standard pizza shapes and specialty formats such as half-pizza slice boxes, roman pizza (rectangular) formats, and deep-dish boxes requiring increased height. All dimensions are manufactured to your specification; there is no standard size catalogue.` },
    { q: `How effective is the heat retention in ${name}?`, a: `The corrugated flute in the walls of ${name} provides passive thermal insulation through the air channels within the board structure — this is the primary heat retention mechanism in standard cardboard pizza boxes. The insulation slows the rate of heat loss from the pizza but does not maintain temperature indefinitely. For applications requiring extended heat retention (extended delivery routes, premium delivery service), insulated liner inserts are available as an upgrade option.` },
    { q: `Can ${name} be branded with our restaurant logo?`, a: `Yes. Full-colour branding is available on the exterior lid, which is the primary brand communication surface visible at the point of delivery or table presentation. Standard flexographic printing on the kraft liner is cost-effective for high-volume orders; litho laminate printing is available for premium print quality. The box base is typically unprinted or printed with a simple functional design.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. Small independent pizzerias and large restaurant chains both order without restriction.` },
    { q: `How do I get a quote for ${name}?`, a: `Complete the form on this page or call ${phone}. Include the sizes you need, the quantity per size, and your logo and brand colours for the lid print. We respond within 24 hours.` },
  ],

  tray: (name, phone) => [
    { q: `Are ${name} food-safe?`, a: `Yes. All ${name} produced for food service applications use food-grade board, food-safe adhesive formulations, and printing inks compliant with Australian food contact regulations. Greaseproof interior coatings are available for trays used with high-fat or high-moisture food products. Food contact material certification documentation is available for the substrates used in your specific order.` },
    { q: `What depth options are available for ${name}?`, a: `We produce ${name} in depths from approximately 15 mm for low-profile display trays through to 80 mm or deeper for food service trays holding substantial portions. The appropriate depth depends on the product — shallow trays for display and product presentation purposes, deeper trays for food service portions that need structural containment. All dimensions are custom; provide the content type and volume and our team will recommend the optimal tray dimensions.` },
    { q: `Can ${name} include dividers for multiple products?`, a: `Yes. Cardboard or board divider inserts are available for ${name} that hold multiple separate products (such as a selection box of different pastries, a tasting tray of cheeses, or a multi-component food service order). Divider configuration and cell dimensions are designed to your specific product layout.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include the tray dimensions, the depth, the quantity, the intended use, and whether food-safe specification or printed branding is required. We respond within 24 hours.` },
  ],

  christmas: (name, phone) => [
    { q: `When should I order ${name} to be ready for the Christmas season?`, a: `Christmas packaging orders should be placed at least 6–8 weeks before your required delivery date to allow for the design, production (7–14 business days), and delivery steps. For the Australian Christmas season, this typically means placing orders no later than late October to ensure comfortable delivery by late November. If you are in doubt about your timeline, contact our team to confirm production capacity — Christmas is our highest-demand production period and early ordering is strongly recommended.` },
    { q: `Can ${name} include festive foil or premium finishes?`, a: `Yes. Gold and silver hot foil stamping are among the most popular embellishments for ${name} — the metallic finish communicates premium gifting quality and creates a festive visual character that resonates strongly in the Christmas retail context. Gloss lamination for maximum colour vibrancy, soft-touch matte for a refined luxury aesthetic, and spot UV over key design elements are all available and popular for Christmas packaging.` },
    { q: `Can ${name} be custom-sized for specific gifts?`, a: `Yes — all dimensions are fully custom. If you are packaging a specific product for Christmas retail, provide the product dimensions and we will design the box dieline around those measurements. We also produce standard gift box proportions (small, medium, large) suitable for a range of gift product types.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. Boutique gift brands ordering 200 units for a seasonal pop-up and retail chains ordering 50,000 branded Christmas boxes both place orders with us.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include your required delivery date, the product dimensions, the quantity, and any existing brand or design files. Please note your Christmas deadline explicitly — our team will flag any timeline concerns immediately in the quote response.` },
  ],

  beverage: (name, phone) => [
    { q: `What formats are available for ${name}?`, a: `Our ${name} are produced in formats appropriate for the wide range of beverages and beverage-adjacent products sold through the Australian specialty food and drink market. Carton formats accommodate retail tin, sachet, and packet configurations. Sleeve boxes with insert trays are used for premium single-serve product collections. Gift box formats with interior dividers hold multiple beverage products (a tea collection, a coffee capsule selection, a functional drink variety pack). Advise our team of the product format (tin, sachet, capsule, bag, bottle) and quantity of units per box and we will recommend the most appropriate packaging structure.` },
    { q: `What print quality is achievable on ${name}?`, a: `Full-colour CMYK printing on SBS clay board delivers photographic-quality colour reproduction for brand imagery, origin photography, flavour profile illustrations, and complex graphic design work. Pantone spot colour matching is available for brands with strict colour consistency requirements across their product range. The specialty food and drink market typically demands higher print quality than standard FMCG packaging — brands in this category use rich, detailed artwork to communicate provenance and craft, and we produce to a standard that represents those values accurately.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. Specialty roasters and tea makers at every scale order without restriction.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include the product format (tin, sachet, capsule, bag), the packaging dimensions required, the quantity, the finish preference, and any existing brand assets or design files. We respond within 24 hours.` },
  ],

  candy: (name, phone) => [
    { q: `Are ${name} food-safe for direct contact with confectionery?`, a: `Yes. All ${name} produced for direct confectionery contact use food-grade board, food-safe interior liner paper, and adhesive formulations compliant with Australian food contact packaging regulations. The interior liner is available in white or gold foil variants. If your confectionery is individually wrapped before going into the box, the food-contact liner specification is not required — standard board without a contact liner is appropriate for products with individual wrappers.` },
    { q: `Can ${name} include a windowed panel?`, a: `Yes. Windowed ${name} use a clear food-safe PET film panel allowing the confectionery inside to be seen without opening the box — effective for products where the visual character of the candy (colour, shape, sugar coating) is a selling point at retail. Window shapes can be rectangular, oval, or custom die-cut to complement your brand design.` },
    { q: `What finish options are available for ${name}?`, a: `Gloss lamination produces maximum colour vibrancy — popular for candy packaging that uses bright, high-energy brand colours. Matte lamination delivers a refined, anti-fingerprint surface. Kraft board with minimal surface finish is used for artisan confectionery brands that want their packaging to communicate natural, handmade values. Gold foil stamping is a popular embellishment for premium gift confectionery.` },
    { q: `Is there a minimum order for ${name}?`, a: `No minimum order quantity. Small confectionery brands and large wholesale suppliers both order without restriction.` },
    { q: `How do I get a quote for ${name}?`, a: `Use the form on this page or call ${phone}. Include the confectionery type, the box dimensions or compartment configuration required, the quantity, the preferred substrate and finish, and whether a window panel or food-contact liner is needed. We respond within 24 hours.` },
  ],

  general: (name, phone) => [
    { q: `What materials are available for ${name}?`, a: `Our ${name} are produced from 300–450 gsm SBS clay board for standard retail and product packaging applications, from kraft board (300–400 gsm) for eco-aligned and artisan brands, from rigid greyboard (1,200–2,400 gsm) for premium box formats, and from corrugated board (single to triple wall) for products requiring transit protection. The most appropriate substrate depends on your product weight, the retail or shipping environment, and your brand's aesthetic and sustainability requirements.` },
    { q: `Is there a minimum order for ${name}?`, a: `No — we have no minimum order quantity. You can order from a single prototype through to a large wholesale production run. Every order, regardless of quantity, receives the same level of design support, print quality, and production care.` },
    { q: `How long does production take for ${name}?`, a: `Standard production is 7–14 business days from the date your artwork is formally approved. Express production (4–7 business days) is available for some formats and order sizes — confirm availability with our team before ordering if you have a specific deadline. The pre-production design step (3D proof and dieline creation) typically takes 3–5 business days from brief confirmation.` },
    { q: `Is the design service really free?`, a: `Yes — completely free. Our in-house graphic designers create your artwork from scratch or adapt your existing brand assets to the structural dieline at no additional charge. You receive a 3D digital mockup and a flat dieline for review before anything goes to print, and you can request as many revision rounds as necessary until every element is exactly right. There are no design fees, setup charges, or hidden costs at any stage of the design process.` },
    { q: `What printing and finishing options are available for ${name}?`, a: `Full-colour CMYK printing with optional Pantone spot colour matching is available on all ${name}. Surface finishes include gloss lamination, matte lamination, soft-touch coating, spot UV varnish, gold and silver hot foil stamping, embossing, and debossing. Multiple finishes can be combined on a single order for layered, premium visual results.` },
    { q: `Do you ship ${name} across all of Australia?`, a: `Yes — we deliver to all Australian states and territories, including New South Wales, Victoria, Queensland, Western Australia, South Australia, Tasmania, the Northern Territory, and the Australian Capital Territory. All orders are dispatched with full tracking from our facility to your nominated delivery address, whether commercial, retail, or residential.` },
    { q: `Can I see a sample before my full order is produced?`, a: `Yes. Pre-production physical samples can be arranged for most packaging formats — contact our team to discuss lead time and cost for your specific product. For most orders, the 3D digital mockup and flat dieline we provide before production are sufficient for accurate approval, covering dimensions, colour, layout, and finish specification. Physical samples are most useful for tactile finish verification on options like soft-touch lamination or embossing.` },
    { q: `What artwork files do you accept?`, a: `We accept Adobe Illustrator (AI), print-ready PDF, EPS, and high-resolution TIFF at a minimum of 300 DPI at the intended print size, with 3mm bleed on all sides and all fonts outlined. If you have no existing artwork, our design team creates it from scratch at no charge. If you are working with an external designer, we can supply the structural dieline template for your specific format for them to build artwork within.` },
    { q: `What quality guarantee applies to ${name}?`, a: `Every order we produce is backed by a quality guarantee. If your ${name} contain a manufacturing defect, a structural fault, or a print result that does not match your approved artwork, we reprint or refund the affected portion of your order without dispute or delay. Contact our team within 7 days of receiving your delivery if you identify a quality concern.` },
    { q: `How do I get a quote for ${name}?`, a: `Complete the quote form on this page with your product dimensions, quantity, material preference, and finish requirements. Our team responds with a detailed, itemised quote within 24 business hours at no obligation. You can also reach us directly on ${phone} to discuss your brief before submitting a formal quote request.` },
  ],

};

export function buildProductFaqs(product: any, phone: string): FAQ[] {
  const type = detectType(product.name, product.categories || []);
  const rawName = product.name.replace(/^Order\s+/i, '').replace(/\s+(?:Wholesale|Packaging)\s*$/i, '').trim();
  const builder = TYPE_FAQS[type];
  return builder(rawName, phone);
}
